name = "next-web-vitals"
pages_build_output_dir = ".vercel/output/static"

compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]
#workers_dev = true

# Analytics Engine 绑定
analytics_engine_datasets = [
  { binding = "web_vitals", dataset = "web_vitals" }
]